In [18]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#import and preprocess data
dataset=pd.read_csv('Finalcombined.csv')
X=dataset.iloc[:,:-1] 
y=dataset.iloc[:,-1]

In [3]:
# split data 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [4]:
X_train

         T    TM    Tm   H   VV     V    VM
561   31.9  37.7  26.7  69  3.2   6.1  13.0
310   14.6  22.0   7.6  63  2.3   6.3  13.0
761   21.2  28.2  14.0  59  2.6   8.9  18.3
564   31.1  36.6  25.6  72  2.9   5.6  11.1
172   29.2  37.8  27.0  89  3.1   6.7  18.3
...    ...   ...   ...  ..  ...   ...   ...
1033  10.6  16.0   6.0  85  1.1   9.8  18.3
763   23.6  30.0  16.0  60  2.3   7.6  16.5
835   28.3  36.1  22.0  63  3.4  13.3  22.2
559   32.4  37.9  27.5  66  3.7  10.0  14.8
684    9.0  14.0   5.0  80  0.6   4.1  13.0

[734 rows x 7 columns]

In [5]:
X_test

         T    TM    Tm   H   VV     V    VM
743   21.2  27.7  16.6  71  2.1  15.4  29.4
656   16.7  23.1   8.6  52  2.4   6.9  18.3
704   11.5  15.8   7.6  97  0.8   6.3  14.8
738   20.3  26.0  13.6  68  1.9   6.7  14.8
496   36.5  42.8  29.8  42  3.4  10.4  20.6
...    ...   ...   ...  ..  ...   ...   ...
50    23.8  31.1  17.0  52  3.1  10.4  18.3
162   31.5  36.2  27.2  76  3.5  12.2  20.6
1007  17.1  24.0  10.0  58  1.9   8.3  16.5
320   12.1  20.2   4.0  61  1.8   4.1  13.0
424   29.8  38.2  21.8  42  3.2   5.9  13.0

[315 rows x 7 columns]

In [6]:
y_train

561      51.95
310     172.64
761      97.72
564      48.40
172      24.36
         ...
1033    136.94
763      98.29
835      19.78
559      36.73
684     256.57
Name: PM 2.5, Length: 734, dtype: float64

In [7]:
y_test

743      87.05
656     148.54
704     154.58
738     119.36
496      61.83
         ...
50       96.00
162      27.30
1007    172.08
320     243.10
424      68.09
Name: PM 2.5, Length: 315, dtype: float64

In [9]:
# build model
from sklearn.linear_model import LinearRegression
LinR=LinearRegression()
LinR.fit(X_train,y_train)

LinearRegression()

In [24]:
y_pred=LinR.predict(X_test)

In [26]:
print(y_pred)

[110.82564724 163.08856619 208.7962436  167.88148174  55.59386221
  85.03172104  80.86217048  59.64541042 259.9645627   50.6292224
 195.64711462 229.98359138  85.01037473  42.82691522  98.42744797
 189.01972418  49.01250782 223.8333373  246.26198717  78.77344095
 252.60913536  71.20904614 206.84466816 212.66853116  79.68779698
 140.21097888 185.2500643   91.78889859 105.36369472 158.36255883
  34.17142179  62.65397866  18.65322135  35.14600814 171.01947868
  82.23178196  36.4631212  229.40579972  33.64901754 117.54805042
 251.35395731 189.46089248 213.00389249  79.2486779   90.67541901
 -25.30457289 147.6687365  135.41193261  47.10552273 132.05799446
 178.14431159  15.99559764  37.92320499 175.53555986  59.10114471
   9.61090572  11.35222205 139.15204187  72.76870502  77.08201704
  59.12326    101.67550606 186.91062408 -13.29236917 232.33271924
 -28.85382365  64.41072137  -5.67238815 147.88664338  87.39687264
  64.64078792 103.88807668 108.20438108  95.45605869 224.08629899
 121.88237411  62.53120535  14.39777215  72.67025875  48.55455455
 142.06419626  90.85815089 242.08224907  91.0517266  216.51567961
 121.64549816 101.39620288  86.18278366 186.66146569  67.44354706
 157.07597496 126.0632614   -5.67111083  67.95142476 150.44371394
  57.37078854 238.99658138  96.72907062  73.40819871 197.58175103
  38.95013706 160.5905389   -3.12248976 160.46188345 105.89935068
 133.95755306  40.69572979 134.35888221  68.58161149  56.36254399
  89.75978814 242.24852985 179.30442999 124.39355329  62.34216026
  55.47814545 100.32152321  52.62552919  51.62651902 250.03944979
  26.40191562   8.40258863 206.50946495 176.57287335 116.07403368
 162.79699841 119.03973731 116.52171728 209.72999283  54.03002063
  24.7983963   44.67561313 172.51442257 170.38565459 197.34698755
 115.908625    58.71119147 173.57503772 119.62988823 204.70437626
 118.5525392   59.097523   185.90030444   7.72427398 155.4314384
 116.2063582    5.78693149  98.4868423  161.15808754  95.50248758
  29.50944205 251.90629641  52.94514879 143.82903361 145.56918047
 132.73750929 175.38641392 143.12358913 110.58513443  26.38627167
  72.98786754 161.49638106  98.70130832 123.80471781 106.82853092
 161.32345697 155.5901852   14.30106717  83.34900734 151.13142235
  60.8213495   81.28523108 101.91805838 169.41979094 156.44340023
  48.84740854 182.4450369   36.1586212    9.65225745 100.60188911
  59.18603808 196.89501997  36.03725904  13.70426421 114.48280955
 220.07791674  66.09630679 102.78318699 119.62084754 126.93615339
  94.62486373  92.15696671 131.97604274 179.93464251  86.58769676
  78.06466548 217.65523771  59.0397971  180.03702146 111.45813417
   2.94753949  -7.52689047 207.81667842  40.18518123 188.87013749
  -1.68751384  26.12947474 124.42102512 -24.68104919  78.05791819
 150.21135576  99.66861121  41.21840986  -8.1559374   47.49936081
 228.6357553   74.18335885   6.32742102 162.66558542  71.29248941
 151.12077745 109.95078277 119.24751658 231.10523077  52.72322566
  36.61481937  55.38177631  36.77311707  74.05819974 238.6965793
  42.51473534 224.1220369   31.22848052 222.65340062 204.68576976
 146.95398418 164.4769511  144.72860612 -22.30346826 253.08791105
 105.8542671   52.35897533   6.99882626 153.08421709 157.97673391
  52.21710491 118.10324539 218.74235136  78.76212339  38.35963028
 152.2668116   -2.36445849   7.12159012 100.32965202  62.70815782
 124.40850292   0.32326391 264.13658894 118.68169347  71.06772447
 145.65279729 184.59279889  83.72395138  99.06993278  30.98994367
 101.81664876 245.22637814 113.68946397 107.00594565 203.05938398
 186.68597163  14.29490386  72.10172277 219.76241159 115.35610719
  99.59094093 207.34881309 144.11394738 201.06544414  75.90111353
  86.53003755 120.64719476  44.82196833 169.83801882  11.46811709
 249.90396654 122.60120551 215.77758769  44.37080004 175.25638683
  58.27839081 239.19360829 106.09920311 167.51856507 154.78245938
 239.11956376 129.11791749 173.38089533  39.19969977  79.98665976
 168.89365644  93.43526037 214.73913684  57.49026527 251.02534488
  50.58549032  70.45870221  55.8546973   84.87826235 170.80682751
  91.16594327  -2.60599813 186.13832596 213.64554028 105.02138184]

In [29]:
# Evaluate model
#R-Squared is also known as the Coefficient of Determination. The value of R-Squared ranges from 0 to 1.
#The higher the R-Squared value of a model, the better is the model fitting on the data. 
#However, if the R-Squared value is very close to 1, then there is a possibility of model overfitting,
#which should be avoided. A good model should have an R-Squared above 0.8.
print(LinR.score(X_train, y_train))
print(LinR.score(X_test, y_test))

0.6819162365647814
0.6938412145242896